### ISSUE TITLE
fetch main error

### ISSUE THREAD

**Issue by sha1thedon** [iAmmarTahir/KnowledgeGraphGPT#5]
when trying to implement the code i receive this error based on the prompt.main file 

Module parse failed: Unexpected token (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> You are given a prompt. Extrapolate as many relationships as you can from the prompt and generate tuples like (source, relation, target). Make sure there are always source, relation and target in the tuple.
| Example:
| prompt: John knows React, Golang, and Python. John is good at Software Engineering and Leadership

**Comment by iAmmarTahir** [comment]
This issue has been fixed.
